# #Use these as an example to create the values file for this application
environment: production
appName: docker-node

containerPort: 3000
containerPortName: web
servicePort: 80
production: blue
ingressPath: "/test"


maxPodReplicas: 10
minPodReplicas: 2
targetCPUUtilizationPercentage: 50

maxSurge: 100%
maxUnavailable: 20%

slotEnabled:
  blue : true
  green: true

image:
  repository: demomfedev.azurecr.io/node-docker
ndots: 5
resources:
  limits:
    cpu: 512m
    memory: 1000Mi
  requests:
    cpu: 512m
    memory: 1000Mi
# app_appName: mango
# inj_branchOrBranchType: release
# inj_deployEnv: ppe1
# app_ingressPath: /*
# app_servicePort: '443'
# app_namespace: mango
# app_azureAcrFqdn: 028ghsprodinfra.azurecr.io
# app_imageName: mango
# app_healthCheckPath: /version
# app_containerPort: '8000'
# app_livenessProbeInitialDelaySeconds: '120'
# app_livenessProbePeriodSeconds: '10'
# app_livenessProbeTimeoutSeconds: '5'
# app_livenessProbeFailureThreshold: '5'
# app_readinessProbeInitialDelaySeconds: '10'
# app_readinessProbePeriodSeconds: '10'
# app_readinessProbeTimeoutSeconds: '5'
# app_readinessProbeFailureThreshold: '10'
# app_cpuRequests: 512m
# app_memoryRequests: 1000Mi
# app_cpuLimits: 512m
# app_memoryLimits: 1000Mi
# inj_acrRepo: mango
# inj_imageVersion: v1.230.0-rc4-8-20200423150436
# taskDef_branch_envType_envVars:
#   APP_ENV: ''
#   KEEP_ALIVE_TIMEOUT_MS: '75000'
#   APPDYNAMICS_TIER_NAME: mango-ppe1-ppe
#   OBJECT_STORAGE_HOSTNAME: ghs028assetsppe.blob.core.windows.net
#   APP_NAME: ppe
#   APPDYNAMICS_ACCESS_KEY: 8285e676c61c
#   DCS_KEY: bc3d0f3c-00f2-47dd-806e-764bdb81e96e
#   SW_SIG: v1.230.0-rc4-8-20200423150436
#   APPDYNAMICS_NODE_NAME: v1.230.0-rc4-8-20200423150436
#   APIGEE_KEY_SAAS: G90bQCO9kd2Dmg6wX9iaELFlE4juc8uq
#   CI_VERSION: v1.230.0-rc4-8-20200423150436
#   MARTINI_DOMAIN: secure-ppe.tesco.com
#   DISCO_DOMAIN: disco.very
#   PLATFORM_FEATURES: '{"PaymentAPICutover":false}'
#   MANGO_PASSWORD: $GGwz,B%a+DpWm[9
#   APM_TOOL: none
#   APP_CONFIGS: ppe
#   PM2env: .azure
#   APIGEE_KEY: vLcsVOP49h1J9YmkfTcSFMXYtg11DmtR
#   CI_BRANCH_NAME: release/v1.230.0
#   APPDYNAMICS_NODE_PREFIX: v1.230.0-rc4-8-20200423150436
#   CSC_UUID: c814f706-0768-3efb-b157-7f699915f6a4
#   NR_LICENSE: f7a896ce5412f8adb4b012d6359ed9186b43f6ec
#   ENABLE_IS_IN_FAVOURITES: 'true'
#   ENV_REGION: ppe1-ppe
#   DEPLOYED: Fri May 01 13:15:22 GMT 2020
#   USING_FEATURES: 'true'
#   OBJECT_STORAGE_ASSETS: /lego-ppe-ui-assets/ppe
#   MANGO_SECRET: 0c4adad1-daa7-42f1-bff4-62cfc835d532
#   OBJECT_STORAGE_ASSETS_SHARED: /lego-ppe-ui-assets/shared
#   APPDYNAMICS_CONTROLLER_HOST: tescodev.saas.appdynamics.com
#   APPDYNAMICS_APP_NAME: 28-mango-ppe1-release-v1.230.0
#   APPDYNAMICS_ACCOUNT_NAME: TescoDev
# taskDef_branch: release
# app_nonProdDNSSubDomain: smapps
# app_productName: mango
# app_teamNumber: '28'